export type Country = {
  code: string; // ISO 3166-1 alpha-2
  name: string;
};

// ISO 3166-1 alpha-2 country list (common names).
export const COUNTRIES: Country[] = [
  { code: 'AF', name: 'Afeganistão' },
  { code: 'AL', name: 'Albânia' },
  { code: 'DZ', name: 'Argélia' },
  { code: 'AS', name: 'Samoa Americana' },
  { code: 'AD', name: 'Andorra' },
  { code: 'AO', name: 'Angola' },
  { code: 'AI', name: 'Anguila' },
  { code: 'AQ', name: 'Antártida' },
  { code: 'AG', name: 'Antígua e Barbuda' },
  { code: 'AR', name: 'Argentina' },
  { code: 'AM', name: 'Arménia' },
  { code: 'AW', name: 'Aruba' },
  { code: 'AU', name: 'Austrália' },
  { code: 'AT', name: 'Áustria' },
  { code: 'AZ', name: 'Azerbaijão' },
  { code: 'BS', name: 'Bahamas' },
  { code: 'BH', name: 'Bahrein' },
  { code: 'BD', name: 'Bangladesh' },
  { code: 'BB', name: 'Barbados' },
  { code: 'BY', name: 'Bielorrússia' },
  { code: 'BE', name: 'Bélgica' },
  { code: 'BZ', name: 'Belize' },
  { code: 'BJ', name: 'Benim' },
  { code: 'BM', name: 'Bermudas' },
  { code: 'BT', name: 'Butão' },
  { code: 'BO', name: 'Bolívia' },
  { code: 'BQ', name: 'Países Baixos Caribenhos' },
  { code: 'BA', name: 'Bósnia e Herzegovina' },
  { code: 'BW', name: 'Botsuana' },
  { code: 'BV', name: 'Ilha Bouvet' },
  { code: 'BR', name: 'Brasil' },
  { code: 'IO', name: 'Território Britânico do Oceano Índico' },
  { code: 'BN', name: 'Brunei' },
  { code: 'BG', name: 'Bulgária' },
  { code: 'BF', name: 'Burquina Faso' },
  { code: 'BI', name: 'Burundi' },
  { code: 'CV', name: 'Cabo Verde' },
  { code: 'KH', name: 'Camboja' },
  { code: 'CM', name: 'Camarões' },
  { code: 'CA', name: 'Canadá' },
  { code: 'KY', name: 'Ilhas Caimão' },
  { code: 'CF', name: 'República Centro-Africana' },
  { code: 'TD', name: 'Chade' },
  { code: 'CL', name: 'Chile' },
  { code: 'CN', name: 'China' },
  { code: 'CX', name: 'Ilha do Natal' },
  { code: 'CC', name: 'Ilhas Cocos (Keeling)' },
  { code: 'CO', name: 'Colômbia' },
  { code: 'KM', name: 'Comores' },
  { code: 'CD', name: 'Congo (RDC)' },
  { code: 'CG', name: 'Congo' },
  { code: 'CK', name: 'Ilhas Cook' },
  { code: 'CR', name: 'Costa Rica' },
  { code: 'CI', name: 'Costa do Marfim' },
  { code: 'HR', name: 'Croácia' },
  { code: 'CU', name: 'Cuba' },
  { code: 'CW', name: 'Curaçau' },
  { code: 'CY', name: 'Chipre' },
  { code: 'CZ', name: 'Chéquia' },
  { code: 'DK', name: 'Dinamarca' },
  { code: 'DJ', name: 'Djibuti' },
  { code: 'DM', name: 'Dominica' },
  { code: 'DO', name: 'República Dominicana' },
  { code: 'EC', name: 'Equador' },
  { code: 'EG', name: 'Egito' },
  { code: 'SV', name: 'El Salvador' },
  { code: 'GQ', name: 'Guiné Equatorial' },
  { code: 'ER', name: 'Eritreia' },
  { code: 'EE', name: 'Estónia' },
  { code: 'SZ', name: 'Essuatíni' },
  { code: 'ET', name: 'Etiópia' },
  { code: 'FK', name: 'Ilhas Falkland (Malvinas)' },
  { code: 'FO', name: 'Ilhas Faroé' },
  { code: 'FJ', name: 'Fiji' },
  { code: 'FI', name: 'Finlândia' },
  { code: 'FR', name: 'França' },
  { code: 'GF', name: 'Guiana Francesa' },
  { code: 'PF', name: 'Polinésia Francesa' },
  { code: 'TF', name: 'Terras Austrais e Antárticas Francesas' },
  { code: 'GA', name: 'Gabão' },
  { code: 'GM', name: 'Gâmbia' },
  { code: 'GE', name: 'Geórgia' },
  { code: 'DE', name: 'Alemanha' },
  { code: 'GH', name: 'Gana' },
  { code: 'GI', name: 'Gibraltar' },
  { code: 'GR', name: 'Grécia' },
  { code: 'GL', name: 'Gronelândia' },
  { code: 'GD', name: 'Granada' },
  { code: 'GP', name: 'Guadalupe' },
  { code: 'GU', name: 'Guam' },
  { code: 'GT', name: 'Guatemala' },
  { code: 'GG', name: 'Guernsey' },
  { code: 'GN', name: 'Guiné' },
  { code: 'GW', name: 'Guiné-Bissau' },
  { code: 'GY', name: 'Guiana' },
  { code: 'HT', name: 'Haiti' },
  { code: 'HM', name: 'Ilha Heard e Ilhas McDonald' },
  { code: 'VA', name: 'Vaticano' },
  { code: 'HN', name: 'Honduras' },
  { code: 'HK', name: 'Hong Kong' },
  { code: 'HU', name: 'Hungria' },
  { code: 'IS', name: 'Islândia' },
  { code: 'IN', name: 'Índia' },
  { code: 'ID', name: 'Indonésia' },
  { code: 'IR', name: 'Irão' },
  { code: 'IQ', name: 'Iraque' },
  { code: 'IE', name: 'Irlanda' },
  { code: 'IM', name: 'Ilha de Man' },
  { code: 'IL', name: 'Israel' },
  { code: 'IT', name: 'Itália' },
  { code: 'JM', name: 'Jamaica' },
  { code: 'JP', name: 'Japão' },
  { code: 'JE', name: 'Jersey' },
  { code: 'JO', name: 'Jordânia' },
  { code: 'KZ', name: 'Cazaquistão' },
  { code: 'KE', name: 'Quénia' },
  { code: 'KI', name: 'Quiribati' },
  { code: 'KP', name: 'Coreia do Norte' },
  { code: 'KR', name: 'Coreia do Sul' },
  { code: 'KW', name: 'Kuwait' },
  { code: 'KG', name: 'Quirguistão' },
  { code: 'LA', name: 'Laos' },
  { code: 'LV', name: 'Letónia' },
  { code: 'LB', name: 'Líbano' },
  { code: 'LS', name: 'Lesoto' },
  { code: 'LR', name: 'Libéria' },
  { code: 'LY', name: 'Líbia' },
  { code: 'LI', name: 'Liechtenstein' },
  { code: 'LT', name: 'Lituânia' },
  { code: 'LU', name: 'Luxemburgo' },
  { code: 'MO', name: 'Macau' },
  { code: 'MG', name: 'Madagáscar' },
  { code: 'MW', name: 'Maláui' },
  { code: 'MY', name: 'Malásia' },
  { code: 'MV', name: 'Maldivas' },
  { code: 'ML', name: 'Mali' },
  { code: 'MT', name: 'Malta' },
  { code: 'MH', name: 'Ilhas Marshall' },
  { code: 'MQ', name: 'Martinica' },
  { code: 'MR', name: 'Mauritânia' },
  { code: 'MU', name: 'Maurícia' },
  { code: 'YT', name: 'Mayotte' },
  { code: 'MX', name: 'México' },
  { code: 'FM', name: 'Micronésia' },
  { code: 'MD', name: 'Moldávia' },
  { code: 'MC', name: 'Mónaco' },
  { code: 'MN', name: 'Mongólia' },
  { code: 'ME', name: 'Montenegro' },
  { code: 'MS', name: 'Montserrat' },
  { code: 'MA', name: 'Marrocos' },
  { code: 'MZ', name: 'Moçambique' },
  { code: 'MM', name: 'Myanmar' },
  { code: 'NA', name: 'Namíbia' },
  { code: 'NR', name: 'Nauru' },
  { code: 'NP', name: 'Nepal' },
  { code: 'NL', name: 'Países Baixos' },
  { code: 'NC', name: 'Nova Caledónia' },
  { code: 'NZ', name: 'Nova Zelândia' },
  { code: 'NI', name: 'Nicarágua' },
  { code: 'NE', name: 'Níger' },
  { code: 'NG', name: 'Nigéria' },
  { code: 'NU', name: 'Niue' },
  { code: 'NF', name: 'Ilha Norfolk' },
  { code: 'MK', name: 'Macedónia do Norte' },
  { code: 'MP', name: 'Ilhas Marianas do Norte' },
  { code: 'NO', name: 'Noruega' },
  { code: 'OM', name: 'Omã' },
  { code: 'PK', name: 'Paquistão' },
  { code: 'PW', name: 'Palau' },
  { code: 'PS', name: 'Palestina' },
  { code: 'PA', name: 'Panamá' },
  { code: 'PG', name: 'Papua-Nova Guiné' },
  { code: 'PY', name: 'Paraguai' },
  { code: 'PE', name: 'Peru' },
  { code: 'PH', name: 'Filipinas' },
  { code: 'PN', name: 'Ilhas Pitcairn' },
  { code: 'PL', name: 'Polónia' },
  { code: 'PT', name: 'Portugal' },
  { code: 'PR', name: 'Porto Rico' },
  { code: 'QA', name: 'Catar' },
  { code: 'RE', name: 'Reunião' },
  { code: 'RO', name: 'Roménia' },
  { code: 'RU', name: 'Rússia' },
  { code: 'RW', name: 'Ruanda' },
  { code: 'BL', name: 'São Bartolomeu' },
  { code: 'SH', name: 'Santa Helena, Ascensão e Tristão da Cunha' },
  { code: 'KN', name: 'São Cristóvão e Nevis' },
  { code: 'LC', name: 'Santa Lúcia' },
  { code: 'MF', name: 'São Martinho (França)' },
  { code: 'PM', name: 'São Pedro e Miquelon' },
  { code: 'VC', name: 'São Vicente e Granadinas' },
  { code: 'WS', name: 'Samoa' },
  { code: 'SM', name: 'San Marino' },
  { code: 'ST', name: 'São Tomé e Príncipe' },
  { code: 'SA', name: 'Arábia Saudita' },
  { code: 'SN', name: 'Senegal' },
  { code: 'RS', name: 'Sérvia' },
  { code: 'SC', name: 'Seicheles' },
  { code: 'SL', name: 'Serra Leoa' },
  { code: 'SG', name: 'Singapura' },
  { code: 'SX', name: 'São Martinho (Países Baixos)' },
  { code: 'SK', name: 'Eslováquia' },
  { code: 'SI', name: 'Eslovénia' },
  { code: 'SB', name: 'Ilhas Salomão' },
  { code: 'SO', name: 'Somália' },
  { code: 'ZA', name: 'África do Sul' },
  { code: 'GS', name: 'Ilhas Geórgia do Sul e Sandwich do Sul' },
  { code: 'SS', name: 'Sudão do Sul' },
  { code: 'ES', name: 'Espanha' },
  { code: 'LK', name: 'Sri Lanka' },
  { code: 'SD', name: 'Sudão' },
  { code: 'SR', name: 'Suriname' },
  { code: 'SJ', name: 'Svalbard e Jan Mayen' },
  { code: 'SE', name: 'Suécia' },
  { code: 'CH', name: 'Suíça' },
  { code: 'SY', name: 'Síria' },
  { code: 'TW', name: 'Taiwan' },
  { code: 'TJ', name: 'Tajiquistão' },
  { code: 'TZ', name: 'Tanzânia' },
  { code: 'TH', name: 'Tailândia' },
  { code: 'TL', name: 'Timor-Leste' },
  { code: 'TG', name: 'Togo' },
  { code: 'TK', name: 'Tokelau' },
  { code: 'TO', name: 'Tonga' },
  { code: 'TT', name: 'Trindade e Tobago' },
  { code: 'TN', name: 'Tunísia' },
  { code: 'TR', name: 'Turquia' },
  { code: 'TM', name: 'Turquemenistão' },
  { code: 'TC', name: 'Ilhas Turks e Caicos' },
  { code: 'TV', name: 'Tuvalu' },
  { code: 'UG', name: 'Uganda' },
  { code: 'UA', name: 'Ucrânia' },
  { code: 'AE', name: 'Emirados Árabes Unidos' },
  { code: 'GB', name: 'Reino Unido' },
  { code: 'US', name: 'Estados Unidos' },
  { code: 'UM', name: 'Ilhas Menores Distantes dos EUA' },
  { code: 'UY', name: 'Uruguai' },
  { code: 'UZ', name: 'Uzbequistão' },
  { code: 'VU', name: 'Vanuatu' },
  { code: 'VE', name: 'Venezuela' },
  { code: 'VN', name: 'Vietname' },
  { code: 'VG', name: 'Ilhas Virgens Britânicas' },
  { code: 'VI', name: 'Ilhas Virgens Americanas' },
  { code: 'WF', name: 'Wallis e Futuna' },
  { code: 'EH', name: 'Saara Ocidental' },
  { code: 'YE', name: 'Iémen' },
  { code: 'ZM', name: 'Zâmbia' },
  { code: 'ZW', name: 'Zimbabué' },
];

export function flagEmojiFromIso2(code: string) {
  const cc = code.toUpperCase();
  if (!/^[A-Z]{2}$/.test(cc)) return '🏳️';
  const base = 0x1f1e6;
  const chars = [...cc].map((c) => base + (c.charCodeAt(0) - 65));
  return String.fromCodePoint(chars[0], chars[1]);
}

